In [40]:
using MCDA
using Test
using LinearAlgebra
using DataFrames

criteria = [
    Criterion("Manpower", 1, 0.116279, identity),
    Criterion("Power", 1.6, 0.186, identity),
    Criterion("Construction", 1.2, 0.13953, identity),
    Criterion("Maintenance", 1, 0.116279, identity),
    Criterion("Villages", 1.8, 0.2093, identity),
    Criterion("Safety", 2, 0.232672, identity),
]

concepts = []

con = Concept("Italy", criteria)
con.values[1] = 1
con.values[2] = 90
con.values[3] = 600
con.values[4] = 5.4
con.values[5] = 8
con.values[6] = 3
push!(concepts, con)
con = Concept("Belgium", criteria)
con.values[1] = 3
con.values[2] = 58
con.values[3] = 200
con.values[4] = 9.7
con.values[5] = 1
con.values[6] = 1
push!(concepts, con)
con = Concept("Germany", criteria)
con.values[1] = 2
con.values[2] = 60
con.values[3] = 400
con.values[4] = 7.2
con.values[5] = 4
con.values[6] = 4
push!(concepts, con)
con = Concept("Sweden", criteria)
con.values[1] = 4
con.values[2] = 80
con.values[3] = 1000
con.values[4] = 7.5
con.values[5] = 7
con.values[6] = 5
push!(concepts, con)
con = Concept("Austria", criteria)
con.values[1] = 4
con.values[2] = 72
con.values[3] = 600
con.values[4] = 2.0
con.values[5] = 3
con.values[6] = 5
push!(concepts, con)
con = Concept("France", criteria)
con.values[1] = 1
con.values[2] = 96
con.values[3] = 700
con.values[4] = 3.6
con.values[5] = 5
con.values[6] = 3
push!(concepts, con)
con = Concept("Spain", criteria)
con.values[1] = 3#2
con.values[2] = 69
con.values[3] = 800
con.values[4] = 2.6
con.values[5] = 2
con.values[6] = 4
push!(concepts, con)
con = Concept("Greece", criteria)
con.values[1] = 2#3
con.values[2] = 62
con.values[3] = 350
con.values[4] = 3.3
con.values[5] = 3
con.values[6] = 3
push!(concepts, con)
con = Concept("Poland", criteria)
con.values[1] = 4#1
con.values[2] = 55
con.values[3] = 450
con.values[4] = 2.7
con.values[5] = 4
con.values[6] = 2
push!(concepts, con)
con = Concept("Denmark", criteria)
con.values[1] = 3#2
con.values[2] = 77
con.values[3] = 550
con.values[4] = 8.1
con.values[5] = 1
con.values[6] = 4
push!(concepts, con)

CMcrit = MCDA.CMcrit(criteria)
matcrit = CMcrit^100/10^57
prioritycrit = sum(matcrit,dims=2)/sum(sum(matcrit))
@show CRcrit = ConsRatio(CMcrit)
# @show p = reverse(sortperm(reshape(prioritycrit,length(prioritycrit))))
# @show collect(1:6)[p]

CMman = MCDA.buildCM(concepts, 1, MCDA.CMScale0_3)
matman = CMman^100/10.0^100
@show priorityman = sum(matman,dims=2)/sum(sum(matman))
@show CRman =ConsRatio(CMman)

CMpow = MCDA.buildCM(concepts, 2, MCDA.CMScale0_maxdiff)
matpow = CMpow^100/10^57
prioritypow = sum(matpow,dims=2)/sum(sum(matpow))
@show CRpow = ConsRatio(CMpow)

CMcon = MCDA.buildCM(concepts, 3, MCDA.CMScale0_maxdiff; smaller_is_better=true)
matcon = CMcon^100/10^57;
prioritycon = sum(matcon,dims=2)/sum(sum(matcon))
@show CRcon = ConsRatio(CMcon)

CMmain = MCDA.buildCM(concepts, 4, MCDA.CMScale0_maxdiff; smaller_is_better=true)
matmain = CMmain^100/10^57
prioritymain = sum(matmain,dims=2)/sum(sum(matmain))
@show CRmain = ConsRatio(CMmain)

CMvil= MCDA.buildCM(concepts, 5, MCDA.CMscale0)
matvil = CMvil^100/10^57
priorityvil = sum(matvil,dims=2)/sum(sum(matvil))
@show CRvil = ConsRatio(CMvil)

CMsaf = MCDA.buildCM(concepts, 6, MCDA.CMScale0_4)
matsaf = CMsaf^100/10.0^100
@show prioritysaf = sum(matsaf,dims=2)/sum(sum(matsaf))
@show CRsaf = ConsRatio(CMsaf)

# for idealized:
# prioritycrit ./= maximum(prioritycrit);
# priorityman ./= maximum(priorityman);
# prioritypow ./= maximum(prioritypow);
# prioritycon ./= maximum(prioritycon);
# prioritymain ./= maximum(prioritymain);
# priorityvil ./= maximum(priorityvil);
# prioritysaf ./= maximum(prioritysaf);

Totalpriority = zeros(10)
for i in 1:10
    # line continuation problem here
    Totalpriority[i] = priorityman[i]*prioritycrit[1]+prioritypow[i]*prioritycrit[2]+prioritycon[i]*prioritycrit[3] +
                       prioritymain[i]*prioritycrit[4]+priorityvil[i]*prioritycrit[5]+prioritysaf[i]*prioritycrit[6]
end

display(Totalpriority)
println()

# alternative method
# priorityall = hcat(priorityman, prioritypow, prioritycon, prioritymain, priorityvil, prioritysaf)
# Totalpriority = priorityall * prioritycrit
# display(Totalpriority)
# println()

CRcrit = ConsRatio(CMcrit) = 2.1812028121701217
priorityman = sum(matman, dims=2) / sum(sum(matman)) = [0.0168197; 0.0872538; 0.0358331; 0.210978; 0.210978; 0.0168197; 0.0872538; 0.0358331; 0.210978; 0.0872538]
CRman = ConsRatio(CMman) = 1.4559587731026573


10-element Array{Float64,1}:
 0.07428317596577252
 0.08326159898899632
 0.08155359674519871
 0.14476317735903138
 0.16249351342367224
 0.09645064706800857
 0.10905481023219148
 0.06914310010968139
 0.05156316352238739
 0.12743321658506002

CRpow = ConsRatio(CMpow) = 2.2261677960755217
CRcon = ConsRatio(CMcon) = 2.004608816887691
CRmain = ConsRatio(CMmain) = 2.0183356289697705
CRvil = ConsRatio(CMvil) = 9.024379771616237
prioritysaf = sum(matsaf, dims=2) / sum(sum(matsaf)) = [0.0480851; 0.0147534; 0.111065; 0.241733; 0.241733; 0.0480851; 0.111065; 0.0480851; 0.0243313; 0.111065]
CRsaf = ConsRatio(CMsaf) = 2.779465755273494



In [77]:
PN = DataFrame(Countries = MCDA.name.(concepts), Total_Priority = Totalpriority)

10×2 DataFrame
│ Row │ Countries │ Total_Priority │
│     │ String    │ Float64        │
├─────┼───────────┼────────────────┤
│ 1   │ Italy     │ 0.0742832      │
│ 2   │ Belgium   │ 0.0832616      │
│ 3   │ Germany   │ 0.0815536      │
│ 4   │ Sweden    │ 0.144763       │
│ 5   │ Austria   │ 0.162494       │
│ 6   │ France    │ 0.0964506      │
│ 7   │ Spain     │ 0.109055       │
│ 8   │ Greece    │ 0.0691431      │
│ 9   │ Poland    │ 0.0515632      │
│ 10  │ Denmark   │ 0.127433       │

In [65]:
df = DataFrame(Priority = String[], Manpower = Float64[], Power = Float64[], Construction = Float64[], Maintenance = Float64[], Villages = Float64[], Safety = Float64[], Total_Priority = Union{Float64,Missing}[])
push!(df, ["Prio criterion", reshape(prioritycrit, length(prioritycrit))..., missing])

1×8 DataFrame. Omitted printing of 3 columns
│ Row │ Priority       │ Manpower  │ Power    │ Construction │ Maintenance │
│     │ String         │ Float64   │ Float64  │ Float64      │ Float64     │
├─────┼────────────────┼───────────┼──────────┼──────────────┼─────────────┤
│ 1   │ Prio criterion │ 0.0332998 │ 0.167636 │ 0.0536592    │ 0.0332998   │

In [62]:
df

0×7 DataFrame

In [58]:
[reshape(prioritycrit, length(prioritycrit))..., missing]

7-element Array{Union{Missing, Float64},1}:
 0.03329975450776186 
 0.16763597044376194 
 0.053659240409722996
 0.03329975450776186 
 0.27435878225399957 
 0.4377464978769918  
  missing            

In [18]:
tf = DataFrame()
tf.Priority =["Prio criterion", "Italy", "Belgium", "Germany", "Sweden", "Austria", "France", "Spain", "Greece", "Poland", "Denmark"]
tf.Manpower =["0.0333", priorityman]
tf

ArgumentError: ArgumentError: New columns must have the same length as old columns

In [7]:
@show prioritycrit

prioritycrit = [0.0332998; 0.167636; 0.0536592; 0.0332998; 0.274359; 0.437746]


6×1 Array{Float64,2}:
 0.03329975450776186 
 0.16763597044376194 
 0.053659240409722996
 0.03329975450776186 
 0.27435878225399957 
 0.4377464978769918  

In [56]:
reshape(prioritycrit, length(prioritycrit))

6-element Array{Float64,1}:
 0.03329975450776186 
 0.16763597044376194 
 0.053659240409722996
 0.03329975450776186 
 0.27435878225399957 
 0.4377464978769918  

In [19]:
priorityman

10×1 Array{Float64,2}:
 0.01681969627380206
 0.08725381517687851
 0.03583307883224336
 0.2109776680857579 
 0.2109776680857579 
 0.01681969627380206
 0.08725381517687851
 0.03583307883224336
 0.2109776680857579 
 0.08725381517687851

In [47]:
@show p = reverse(sortperm(reshape(prioritycrit,length(prioritycrit))))
@show collect(1:6)[p]

p = reverse(sortperm(reshape(prioritycrit, length(prioritycrit)))) = [6, 5, 2, 3, 4, 1]
(collect(1:6))[p] = [6, 5, 2, 3, 4, 1]


6-element Array{Int64,1}:
 6
 5
 2
 3
 4
 1

In [74]:
length(prioritycrit)+1 .- sortperm(reshape(prioritycrit,length(prioritycrit)))

6-element Array{Int64,1}:
 6
 3
 4
 5
 2
 1

In [43]:
prioritycrit

6×1 Array{Float64,2}:
 0.03329975450776186 
 0.16763597044376194 
 0.053659240409722996
 0.03329975450776186 
 0.27435878225399957 
 0.4377464978769918  

In [49]:
MCDA.name.(concepts)

10-element Array{String,1}:
 "Italy"  
 "Belgium"
 "Germany"
 "Sweden" 
 "Austria"
 "France" 
 "Spain"  
 "Greece" 
 "Poland" 
 "Denmark"

In [78]:
DataFrame(Priority = ["Prio criterion", MCDA.name.(concepts)...], Manpower = [prioritycrit[1], priorityman...], Power = [prioritycrit[2], prioritypow...])

11×3 DataFrame
│ Row │ Priority       │ Manpower  │ Power     │
│     │ String         │ Float64   │ Float64   │
├─────┼────────────────┼───────────┼───────────┤
│ 1   │ Prio criterion │ 0.0332998 │ 0.167636  │
│ 2   │ Italy          │ 0.0168197 │ 0.229022  │
│ 3   │ Belgium        │ 0.0872538 │ 0.0239292 │
│ 4   │ Germany        │ 0.0358331 │ 0.0286996 │
│ 5   │ Sweden         │ 0.210978  │ 0.114841  │
│ 6   │ Austria        │ 0.210978  │ 0.0675364 │
│ 7   │ France         │ 0.0168197 │ 0.326815  │
│ 8   │ Spain          │ 0.0872538 │ 0.0566147 │
│ 9   │ Greece         │ 0.0358331 │ 0.0292572 │
│ 10  │ Poland         │ 0.210978  │ 0.0202856 │
│ 11  │ Denmark        │ 0.0872538 │ 0.103     │